/**
 * TRACE x MemWal Integration
 * 
 * Uses MemWal (Walrus Memory) as the agent's persistent memory layer.
 * 
 * What this enables:
 * - Agent memories are encrypted and stored on Walrus via MemWal
 * - Semantic search over past verifications — "recall all AI-generated images from BBC"
 * - Cross-session persistence — agent remembers everything across restarts
 * - Cross-agent sharing — any other agent with the account ID reads the same memory
 * - Verifiable — cryptographic proof memories haven't been tampered with
 */

import { MemWal } from "@mysten-incubation/memwal";

// ── MemWal client factory ─────────────────────────────────────────────────────
let _client: MemWal | null = null;

export function getMemWalClient(): MemWal | null {
  if (_client) return _client;

  const key       = process.env.MEMWAL_PRIVATE_KEY;
  const accountId = process.env.MEMWAL_ACCOUNT_ID;

  if (!key || !accountId) {
    console.warn("[MemWal] MEMWAL_PRIVATE_KEY or MEMWAL_ACCOUNT_ID not set — using file fallback");
    return null;
  }

  _client = MemWal.create({
    key,
    accountId,
    namespace: "trace-agent",
  });

  console.log("[MemWal] Client initialised — namespace: trace-agent");
  return _client;
}

// ── Core memory operations ────────────────────────────────────────────────────

/**
 * Store a verification result in MemWal
 * Each memory is a natural language description of what the agent found
 */
export async function rememberVerification(params: {
  imageUrl:   string;
  source:     string;
  verdict:    string;
  confidence: number;
  hash:       string;
  mediaId?:   string;
}): Promise<string | null> {
  const client = getMemWalClient();
  if (!client) return null;

  const { imageUrl, source, verdict, confidence, hash, mediaId } = params;

  // Format as natural language so recall() can do semantic search
  const memory = [
    `Image from ${source} was verified as ${verdict} with ${(confidence * 100).toFixed(0)}% confidence.`,
    `SHA-256 hash: ${hash}.`,
    mediaId ? `Registered in TRACE registry with media ID: ${mediaId}.` : `Not found in TRACE registry.`,
    `Image URL: ${imageUrl}.`,
    `Verified at: ${new Date().toISOString()}.`,
    verdict === "VERIFIED_ORIGINAL"
      ? "This image has cryptographic provenance proof on Sui blockchain."
      : verdict === "AI_GENERATED"
      ? "This image appears to be synthetically generated by AI."
      : verdict === "MODIFIED"
      ? "This image has been edited but its origin is traceable on-chain."
      : "This image has no provenance record in the TRACE registry.",
  ].join(" ");

  try {
    const result = await client.rememberAndWait(memory, "verifications");
    console.log(`[MemWal] Stored verification memory — blob: ${result.blob_id}`);
    return result.blob_id;
  } catch (err) {
    console.warn("[MemWal] remember failed:", err);
    return null;
  }
}

/**
 * Store a full agent session report in MemWal
 */
export async function rememberSession(session: {
  sessionId:      number;
  sourcesChecked: string[];
  totalScanned:   number;
  verdicts:       Record<string, number>;
  alerts:         number;
  walrusBlobId?:  string;
}): Promise<string | null> {
  const client = getMemWalClient();
  if (!client) return null;

  const { sessionId, sourcesChecked, totalScanned, verdicts, alerts, walrusBlobId } = session;

  const memory = [
    `Agent session ${sessionId} completed at ${new Date().toISOString()}.`,
    `Scanned ${totalScanned} images from ${sourcesChecked.join(", ")}.`,
    Object.entries(verdicts).map(([v, c]) => `${c} images were ${v}`).join(". ") + ".",
    alerts > 0
      ? `ALERT: ${alerts} unverified images detected spreading across multiple sources.`
      : "No coordinated misinformation detected this session.",
    walrusBlobId
      ? `Full session data archived on Walrus: ${walrusBlobId}.`
      : "",
  ].filter(Boolean).join(" ");

  try {
    const result = await client.rememberAndWait(memory, "sessions");
    console.log(`[MemWal] Stored session memory — blob: ${result.blob_id}`);
    return result.blob_id;
  } catch (err) {
    console.warn("[MemWal] session remember failed:", err);
    return null;
  }
}

/**
 * Recall relevant memories using natural language query
 * This is the semantic search power of MemWal
 */
export async function recallMemories(query: string, limit = 5): Promise<{
  text:     string;
  blob_id:  string;
  distance: number;
}[]> {
  const client = getMemWalClient();
  if (!client) return [];

  try {
    const result = await client.recall({ query, limit, namespace: "verifications" });
    return result.results;
  } catch (err) {
    console.warn("[MemWal] recall failed:", err);
    return [];
  }
}

/**
 * Recall session history
 */
export async function recallSessions(query: string, limit = 3): Promise<{
  text:     string;
  blob_id:  string;
  distance: number;
}[]> {
  const client = getMemWalClient();
  if (!client) return [];

  try {
    const result = await client.recall({ query, limit, namespace: "sessions" });
    return result.results;
  } catch (err) {
    console.warn("[MemWal] session recall failed:", err);
    return [];
  }
}

/**
 * Check MemWal health
 */
export async function checkMemWalHealth(): Promise<{
  connected: boolean;
  status?:   string;
  version?:  string;
}> {
  const client = getMemWalClient();
  if (!client) return { connected: false };

  try {
    const health = await client.health();
    return { connected: true, status: health.status, version: health.version };
  } catch {
    return { connected: false };
  }
}